### ISSUE TITLE
Homework feedback

### ISSUE THREAD

**Issue by npmSteven** [Samwakelam/04_WEB_API_CODING_QUIZ_SLW#1]
**What did you do well?**
* Application user experience is intuitive and easy to navigate
* Application user interface style is clean and polished
* Application resembles the mock-up functionality provided in homework instructions

**Needs improvement**
* Remove commented out code
* Remove any console.log that isn't being used to handle errors
* Repository README is missing 1 of the following: description, screenshot, or link to the deployed application

**Suggested improvements (Doesn't affect grade)**
* You shouldn't name JavaScript files `javascript`, you should use a more meaningful name such as `main.js`.
* When you are adding a commit says what you did for example `Added index.html with default HTML`

**GRADE**: A-
[BCS](https://bootcampspot.com/gradebook/79274/grade/63805)

**Comment by Samwakelam** [comment]
@StevenRafferty , Amendments made, I have commented out console.logs, remain for future testing, however i have removed the pseudo code and renamed the javascript as I believe I have understood. 

Thank you very much! 

Please update me again if you see anything more.

**Comment by Samwakelam** [comment]
@StevenRafferty  I have added additional features that the central grader asked for.

**Comment by sol3uk** [comment]
### Updated Feedback
**What did you do well?**
* Application user experience is intuitive and easy to navigate
* Application user interface style is clean and polished
* Application resembles the mock-up functionality provided in homework instructions
 
**Suggested improvements (Doesn't affect grade)**
* Remove commented out code (you don't need to keep console.logs commented out, just remove them)
* You shouldn't name JavaScript files `javascript`, you should use a more meaningful name such as `main.js`.
* You should ideally only have the single JS file, not 2 different files with duplicated code for no reason.
* Change to using "let" and "const" rather than "var" everywhere.
* I did find a bug that I could click the same answer multiple times (or different answers before it changed question) and it would cause improper functionality.
 
**GRADE**: A+
[BCS](https://bootcampspot.com/gradebook/79274/grade/63805)

**Comment by sol3uk** [comment]
@Samwakelam please see updated feedback above, I have updated your grade in BCS too, well done! 😄
